using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema; 

namespace TaskManagerCore.SQL.Sqlite.Entity
{
    /// <summary>
    /// Base object for Entity objects
    /// </summary>
    public class EntityBaseV2
    {
        /// <summary>
        /// Auto-generated SQL Database ID 
        /// </summary>
        [Key]
        public long Id { get; set; } // for auto generated id in database

        /// <summary>
        /// GUID Generated by Task Manager
        /// </summary>
        public string GlobalId { get; set; }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="globalId"></param>
        protected EntityBaseV2(string globalId = "")
        {
            if (globalId != null && globalId != string.Empty)
            {
                GlobalId = globalId;
            } else
            {
                GlobalId = string.Empty;
            }
        }
    }
}
